# Data Preprocessing-Before Building Machine learnig model

#STEPS of preprocessing of data\
step:1]- Import neccessary library\
step:2]- Read Dataset\
step:3]- sanity check of data\
step:4]- Exploratory Data Analysis(EDA)

### step:1]- Import neccessary library

In [127]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

import warnings
warnings.filterwarnings("ignore", category=RuntimeWarning)
warnings.filterwarnings("ignore", category=FutureWarning)

pd.set_option('display.max_columns', None)

### step:2]- Read Dataset

In [128]:
df = pd.read_csv(r"E:\DEPI\Food Project\Nutrition.csv")

In [129]:
#head
df.head()

,commodity,calories (Kcal),protein (g),carbs (g),fat (g),iron (mg),vitamin C (mg)
0,Pasta,370,13.0,75.0,1.5,1.3,0.0
1,Potatoes,77,2.0,17.0,0.1,0.8,19.7
2,Rice,360,7.0,80.0,0.6,0.8,0.0
3,Wheat flour,364,10.0,76.0,1.0,1.2,0.0
4,Meat (beef),250,26.0,0.0,15.0,2.6,0.0

In [130]:
#tail
df.tail()

,commodity,calories (Kcal),protein (g),carbs (g),fat (g),iron (mg),vitamin C (mg)
26,"Cheese (local, processed, Nesto)",310,11.0,4.0,28.0,0.1,0.0
27,Oil (cotton),884,0.0,0.0,100.0,0.0,0.0
28,"Meat (chicken, farm)",215,18.0,0.0,15.0,1.0,0.0
29,Cucumbers (medium sized),15,0.7,3.6,0.1,0.3,2.8
30,Milk (fresh),61,3.2,4.8,3.3,0.0,0.0

In [131]:
df.columns

Index(['commodity', 'calories (Kcal)', 'protein (g)', 'carbs (g)', 'fat (g)',
       'iron (mg)', 'vitamin C (mg)'],
      dtype='object')

In [134]:
df.head()

,commodity,calories (Kcal),protein (g),carbs (g),fat (g),iron (mg),vitamin C (mg)
0,Pasta,370,13.0,75.0,1.5,1.3,0.0
1,Potatoes,77,2.0,17.0,0.1,0.8,19.7
2,Rice,360,7.0,80.0,0.6,0.8,0.0
3,Wheat flour,364,10.0,76.0,1.0,1.2,0.0
4,Meat (beef),250,26.0,0.0,15.0,2.6,0.0

In [135]:
df[df['vitamin C (mg)']>=1].count()

commodity          8
calories (Kcal)    8
protein (g)        8
carbs (g)          8
fat (g)            8
iron (mg)          8
vitamin C (mg)     8
dtype: int64

### step:3]- sanity check of data

In [136]:
#shape
df.shape

(31, 7)

In [137]:
#info()
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 31 entries, 0 to 30
Data columns (total 7 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   commodity        31 non-null     object
 1   calories (Kcal)  31 non-null     int64
 2   protein (g)      31 non-null     float64
 3   carbs (g)        31 non-null     float64
 4   fat (g)          31 non-null     float64
 5   iron (mg)        31 non-null     float64
 6   vitamin C (mg)   31 non-null     float64
dtypes: float64(5), int64(1), object(1)
memory usage: 1.8+ KB

In [138]:
#finding missing value
df.isnull().sum()

commodity          0
calories (Kcal)    0
protein (g)        0
carbs (g)          0
fat (g)            0
iron (mg)          0
vitamin C (mg)     0
dtype: int64

In [139]:
#Percentage of missing values
df.isnull().sum()/df.shape[0]*100

commodity          0.0
calories (Kcal)    0.0
protein (g)        0.0
carbs (g)          0.0
fat (g)            0.0
iron (mg)          0.0
vitamin C (mg)     0.0
dtype: float64

In [140]:
df.columns

Index(['commodity', 'calories (Kcal)', 'protein (g)', 'carbs (g)', 'fat (g)',
       'iron (mg)', 'vitamin C (mg)'],
      dtype='object')

In [141]:
df = df[['commodity', 'calories (Kcal)', 'protein (g)', 'carbs (g)', 'fat (g)',
       'iron (mg)']]

In [142]:
#Percentage of missing values
df.isnull().sum()/df.shape[0]*100

commodity          0.0
calories (Kcal)    0.0
protein (g)        0.0
carbs (g)          0.0
fat (g)            0.0
iron (mg)          0.0
dtype: float64

In [143]:
#finding duplicates
df.duplicated().all().sum()

0

In [144]:
df['commodity'].unique()

array(['Pasta', 'Potatoes', 'Rice', 'Wheat flour', 'Meat (beef)',
       'Meat (chicken, frozen)', 'Sugar', 'Ghee (natural)', 'Oil (maize)',
       'Lentils', 'Onions (red)', 'Tomatoes', 'Ghee (artificial)',
       'Garlic', 'Onions (white)', 'Beans (fava, dry)', 'Eggs',
       'Oil (sunflower)', 'Fish (tilapia)', 'Cheese', 'Cheese (picon)',
       'Milk', 'Oil (mixed)', 'Meat (beef, without bones)',
       'Wheat flour (unpacked, 72%)', 'Eggs (medium size)',
       'Cheese (local, processed, Nesto)', 'Oil (cotton)',
       'Meat (chicken, farm)', 'Cucumbers (medium sized)', 'Milk (fresh)'],
      dtype=object)

In [145]:
#identifiying garbage values
for i in df.select_dtypes(include="object").columns:
    print(df[i].value_counts())
    print("****"*10)

commodity
Pasta                               1
Eggs                                1
Cucumbers (medium sized)            1
Meat (chicken, farm)                1
Oil (cotton)                        1
Cheese (local, processed, Nesto)    1
Eggs (medium size)                  1
Wheat flour (unpacked, 72%)         1
Meat (beef, without bones)          1
Oil (mixed)                         1
Milk                                1
Cheese (picon)                      1
Cheese                              1
Fish (tilapia)                      1
Oil (sunflower)                     1
Beans (fava, dry)                   1
Potatoes                            1
Onions (white)                      1
Garlic                              1
Ghee (artificial)                   1
Tomatoes                            1
Onions (red)                        1
Lentils                             1
Oil (maize)                         1
Ghee (natural)                      1
Sugar                               1
Meat (chicken, frozen)              1
Meat (beef)                         1
Wheat flour                         1
Rice                                1
Milk (fresh)                        1
Name: count, dtype: int64
****************************************

In [146]:
# كود ذكي للكشف عن القيم المشكوك فيها (Garbage Detection)
garbage_report = {}

for col in df.select_dtypes(include="object").columns:
    counts = df[col].value_counts()
    
    # هنطلع القيم اللي اتكررت أقل من 3 مرات (احتمال كبير تكون غلطة إملائية)
    rare_values = counts[counts < 3].index.tolist()
    
    # هنطلع الكلمات اللي فيها رموز مش حروف (زي ? أو #)
    suspicious_chars = [val for val in counts.index if any(char in str(val) for char in ['?', '#', '!', '*'])]
    
    if rare_values or suspicious_chars:
        garbage_report[col] = {
            "Rare Values (Possible Typos)": rare_values,
            "Suspicious Symbols": suspicious_chars
        }

# عرض التقرير
if not garbage_report:
    print("✨ البيانات نظيفة زي الفل مفيش قيم غريبة واضحة!")
else:
    for col, issues in garbage_report.items():
        print(f"🔍 العمود: 【{col}】")
        if issues["Rare Values (Possible Typos)"]:
            print(f"   - قيم نادرة (ممكن تكون غلطات): {issues['Rare Values (Possible Typos)']}")
        if issues["Suspicious Symbols"]:
            print(f"   - رموز مشبوهة: {issues['Suspicious Symbols']}")
        print("-" * 30)

🔍 العمود: 【commodity】
   - قيم نادرة (ممكن تكون غلطات): ['Pasta', 'Eggs', 'Cucumbers (medium sized)', 'Meat (chicken, farm)', 'Oil (cotton)', 'Cheese (local, processed, Nesto)', 'Eggs (medium size)', 'Wheat flour (unpacked, 72%)', 'Meat (beef, without bones)', 'Oil (mixed)', 'Milk', 'Cheese (picon)', 'Cheese', 'Fish (tilapia)', 'Oil (sunflower)', 'Beans (fava, dry)', 'Potatoes', 'Onions (white)', 'Garlic', 'Ghee (artificial)', 'Tomatoes', 'Onions (red)', 'Lentils', 'Oil (maize)', 'Ghee (natural)', 'Sugar', 'Meat (chicken, frozen)', 'Meat (beef)', 'Wheat flour', 'Rice', 'Milk (fresh)']
------------------------------

### step:4]- Exploratory Data Analysis(EDA)

In [147]:
#descriptive statistics
df.describe().T

,count,mean,std,min,25%,50%,75%,max
calories (Kcal),31.0,343.258065,295.212236,15.0,135.50,300.0,378.5,884.0
protein (g),31.0,9.900000,10.204868,0.0,0.80,7.0,15.5,28.0
carbs (g),31.0,20.012903,31.350489,0.0,0.00,3.9,25.0,100.0
fat (g),31.0,25.051613,38.314896,0.0,0.80,3.3,27.0,100.0
iron (mg),31.0,1.093548,1.777814,0.0,0.05,0.6,1.2,7.5

In [148]:
df.describe(include="object").T

          count unique    top freq
commodity    31     31  Pasta    1

In [149]:
df.select_dtypes(include="number").columns

Index(['calories (Kcal)', 'protein (g)', 'carbs (g)', 'fat (g)', 'iron (mg)'], dtype='object')

In [150]:
df.to_csv('final nutrition data.csv', index=False)